baseurl: http://medv.io
markdown: kramdown
permalink: :title/
paginate: 10
exclude:
  - node_modules
  - src
  - vendor
  - bower.json
  - CNAME
  - gulpfile.js
  - package.json
  - README.md
gems:
  - jekyll-feed
  - jekyll-paginate
